@namespace
class SpriteKind:
    alien = SpriteKind.create()
    newalien = SpriteKind.create()

def on_up_pressed():
    if Astronaut.vy == 0:
        Astronaut.vy += -150
        animation.run_image_animation(Astronaut,
            [img("""
                    ................................
                                ................................
                                ................................
                                ................................
                                ................................
                                ................................
                                ................................
                                ................................
                                ............111111..............
                                ...........11ffff11.............
                                ..........11f1ffff11............
                                .........1ff1fffffff1...........
                                ........1ff1fffffffff1..........
                                ........1ffffffffffff1..........
                                ........1ffffffffffff1..........
                                .........1ffffffff1f1...........
                                .........1fffffff1ff1...........
                                ..........1fffff1ff1............
                                ...........1ffffff1.............
                                ...........11111111.............
                                ..........11f1111f11............
                                .......1111f1f11f1f111..........
                                ......1f1111f11f11f11f1.........
                                .....ff1..1111f11f11.1ff........
                                .....ff...111f11f111..ff........
                                .....42....11f1f111...24........
                                .....442....11f111...244........
                                .....442...11111111..244........
                                .....42...111....111..24........
                                ......2...1ff....ff1..2.........
                                ........1fff......fff1..........
                                ........111........111..........
                """),
                img("""
                    ................................
                                ................................
                                ................................
                                ................................
                                ................................
                                ................................
                                ................................
                                ................................
                                .............111111.............
                                ............11ffff11............
                                ...........11f1ffff11...........
                                ..........1ff1fffffff1..........
                                .........1ff1fffffffff1.........
                                .........1ffffffffffff1.........
                                .........1ffffffffffff1.........
                                ..........1ffffffff1f1..........
                                ..........1fffffff1ff1..........
                                ...........1fffff1ff1...........
                                ............1ffffff1............
                                ......ff....11111111....ff......
                                ......ff1..11f1111f11..1ff......
                                .......1f111f1f11f1f111f1.......
                                ........11111f11f11f1111........
                                ...........1111f11f11...........
                                ...........111f11f111...........
                                ............11f1f111............
                                .............11f111.............
                                ............11111111............
                                ...........111....111...........
                                ...........1ff....ff1...........
                                .........1fff......fff1.........
                                .........111........111.........
                """)],
            300,
            False)
controller.up.on_event(ControllerButtonEvent.PRESSED, on_up_pressed)

def spawn_enemies():
    global alien2
    for value in tiles.get_tiles_by_type(assets.tile("""
        spawner
    """)):
        alien2 = sprites.create(assets.image("""
            ailen
        """), SpriteKind.newalien)
        tiles.place_on_tile(alien2, value)
        tiles.set_tile_at(value, assets.tile("""
            transparency16
        """))
        alien2.follow(Astronaut, 25)
        alien2.set_stay_in_screen(True)

def on_overlap_tile(sprite, location):
    if controller.up.is_pressed():
        Astronaut.vy = -75
        Astronaut.start_effect(effects.bubbles, 200)
    animation.run_image_animation(Astronaut,
        assets.animation("""
            waterjump
        """),
        500,
        False)
scene.on_overlap_tile(SpriteKind.player,
    assets.tile("""
        Water
    """),
    on_overlap_tile)

def on_overlap_tile2(sprite2, location2):
    tiles.load_map(tiles.create_map(tilemap("""
        level4
    """)))
    Astronaut.set_position(1, 1)
scene.on_overlap_tile(SpriteKind.player,
    assets.tile("""
        blackhole
    """),
    on_overlap_tile2)

def on_overlap_tile3(sprite3, location3):
    Astronaut.set_image(img("""
        ................................
                ................................
                ................................
                ................................
                ................................
                ................................
                ................................
                ................................
                ................................
                ................................
                ................................
                ................................
                ................................
                ................................
                ................................
                ................................
                ................................
                ................................
                ................................
                ................................
                ................................
                ................................
                ................................
                ................................
                ................................
                ................................
                ................................
                ................................
                ................................
                ................................
                ................................
                ................................
    """))
    
    def on_debounce():
        game.game_over(False)
        game.set_game_over_effect(False, color.fade_to_black)
    timer.debounce("action", 500, on_debounce)
    
scene.on_overlap_tile(SpriteKind.player,
    assets.tile("""
        dark
    """),
    on_overlap_tile3)

def on_overlap_tile4(sprite4, location4):
    if controller.down.is_pressed():
        game.show_long_text("You have landed on the planet of Tartep.", DialogLayout.TOP)
        game.show_long_text("It is rich with information about the universe  ",
            DialogLayout.TOP)
        game.show_long_text("but there are many goober outpost staitioned there. ",
            DialogLayout.TOP)
scene.on_overlap_tile(SpriteKind.player,
    assets.tile("""
        info dot
    """),
    on_overlap_tile4)

def on_overlap_tile5(sprite5, location5):
    if controller.down.is_pressed():
        game.show_long_text("Water is usefull for getting around quickly",
            DialogLayout.TOP)
scene.on_overlap_tile(SpriteKind.player,
    assets.tile("""
        info 2
    """),
    on_overlap_tile5)

alien2: Sprite = None
Astronaut: Sprite = None
info.set_life(5)
tiles.place_on_tile(Astronaut, tiles.get_tile_location(8, 6))
scene.set_background_image(assets.image("""
    Space
"""))
Astronaut = sprites.create(assets.image("""
    Astronaut
"""), SpriteKind.player)
controller.move_sprite(Astronaut, 150, 0)
scene.camera_follow_sprite(Astronaut)
tiles.set_current_tilemap(tilemap("""
    level0
"""))
tiles.place_on_random_tile(Astronaut, sprites.castle.rock0)
game.show_long_text("Welcome to Mission: Universe.", DialogLayout.TOP)
game.show_long_text("Use the Arrow Keys to Move and Space to Jump ",
    DialogLayout.TOP)
game.show_long_text("Your Job is to collect information about the universe for the government",
    DialogLayout.TOP)
game.show_long_text("But beware of the evil alien organization; Goober ",
    DialogLayout.TOP)
game.show_long_text("They are trying to steal information to take over the world",
    DialogLayout.TOP)

def on_on_update():
    if (Astronaut.is_hitting_tile(CollisionDirection.LEFT) or Astronaut.is_hitting_tile(CollisionDirection.RIGHT)) and Astronaut.vy >= 0:
        Astronaut.vy = 0
        Astronaut.ay = 0
    else:
        Astronaut.ay = 250
    if Astronaut.vx < 0 or Astronaut.is_hitting_tile(CollisionDirection.LEFT):
        pass
    Astronaut.set_image(Astronaut.image)
    if Astronaut.vx < 0:
        pass
game.on_update(on_on_update)
