namespace SpriteKind {
    export const alien = SpriteKind.create()
    export const newalien = SpriteKind.create()
}
controller.up.onEvent(ControllerButtonEvent.Pressed, function () {
    if (Astronaut.vy == 0) {
        Astronaut.vy += -150
        animation.runImageAnimation(
        Astronaut,
        [img`
            ................................
            ................................
            ................................
            ................................
            ................................
            ................................
            ................................
            ................................
            ............111111..............
            ...........11ffff11.............
            ..........11f1ffff11............
            .........1ff1fffffff1...........
            ........1ff1fffffffff1..........
            ........1ffffffffffff1..........
            ........1ffffffffffff1..........
            .........1ffffffff1f1...........
            .........1fffffff1ff1...........
            ..........1fffff1ff1............
            ...........1ffffff1.............
            ...........11111111.............
            ..........11f1111f11............
            .......1111f1f11f1f111..........
            ......1f1111f11f11f11f1.........
            .....ff1..1111f11f11.1ff........
            .....ff...111f11f111..ff........
            .....42....11f1f111...24........
            .....442....11f111...244........
            .....442...11111111..244........
            .....42...111....111..24........
            ......2...1ff....ff1..2.........
            ........1fff......fff1..........
            ........111........111..........
            `,img`
            ................................
            ................................
            ................................
            ................................
            ................................
            ................................
            ................................
            ................................
            .............111111.............
            ............11ffff11............
            ...........11f1ffff11...........
            ..........1ff1fffffff1..........
            .........1ff1fffffffff1.........
            .........1ffffffffffff1.........
            .........1ffffffffffff1.........
            ..........1ffffffff1f1..........
            ..........1fffffff1ff1..........
            ...........1fffff1ff1...........
            ............1ffffff1............
            ......ff....11111111....ff......
            ......ff1..11f1111f11..1ff......
            .......1f111f1f11f1f111f1.......
            ........11111f11f11f1111........
            ...........1111f11f11...........
            ...........111f11f111...........
            ............11f1f111............
            .............11f111.............
            ............11111111............
            ...........111....111...........
            ...........1ff....ff1...........
            .........1fff......fff1.........
            .........111........111.........
            `],
        300,
        false
        )
    }
})
scene.onOverlapTile(SpriteKind.Player, assets.tile`Water`, function (sprite, location) {
    if (controller.up.isPressed()) {
        Astronaut.vy = -75
        Astronaut.startEffect(effects.bubbles, 200)
    }
    animation.runImageAnimation(
    Astronaut,
    assets.animation`waterjump`,
    500,
    false
    )
})
function spawn_enemies () {
    for (let value of tiles.getTilesByType(assets.tile`spawner`)) {
        alien2 = sprites.create(assets.image`ailen`, SpriteKind.newalien)
        tiles.placeOnTile(alien2, value)
        tiles.setTileAt(value, assets.tile`transparency16`)
        if (Math.percentChance(50)) {
            alien2.vx = 50
        } else {
            alien2.vx = -50
        }
        alien2.setBounceOnWall(true)
    }
}
scene.onOverlapTile(SpriteKind.Player, assets.tile`dark`, function (sprite3, location3) {
    Astronaut.setImage(img`
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        `)
    timer.debounce("action", 500, function () {
        game.gameOver(false)
        game.setGameOverEffect(false, color.FadeToBlack)
    })
})
sprites.onOverlap(SpriteKind.Player, SpriteKind.newalien, function (sprite, otherSprite) {
    if (sprite.bottom < otherSprite.y && sprite.vy > 0) {
        sprites.destroy(otherSprite)
        Astronaut.vy = -100
        music.play(music.melodyPlayable(music.baDing), music.PlaybackMode.UntilDone)
        info.changeScoreBy(2)
    } else {
        info.changeLifeBy(-1)
        Astronaut.sayText("Ouch", 500, false)
        pause(1000)
        music.play(music.melodyPlayable(music.zapped), music.PlaybackMode.UntilDone)
    }
})
scene.onOverlapTile(SpriteKind.Player, assets.tile`info 2`, function (sprite5, location5) {
    if (controller.down.isPressed()) {
        game.showLongText("Water is usefull for getting around quickly", DialogLayout.Top)
    }
})
scene.onOverlapTile(SpriteKind.Player, assets.tile`info dot`, function (sprite4, location4) {
    if (controller.down.isPressed()) {
        game.showLongText("You have landed on the planet of Tartep.", DialogLayout.Top)
        game.showLongText("It is rich with information about the universe  ", DialogLayout.Top)
        game.showLongText("but there are many goober outpost staitioned there. ", DialogLayout.Top)
    }
})
scene.onOverlapTile(SpriteKind.Player, assets.tile`blackhole`, function (sprite2, location2) {
    tiles.loadMap(tiles.createMap(tilemap`level4`))
    Astronaut.setPosition(10, 75)
})
let alien2: Sprite = null
let Astronaut: Sprite = null
info.setLife(5)
tiles.placeOnTile(Astronaut, tiles.getTileLocation(8, 6))
scene.setBackgroundImage(assets.image`Space`)
Astronaut = sprites.create(assets.image`Astronaut`, SpriteKind.Player)
controller.moveSprite(Astronaut, 150, 0)
scene.cameraFollowSprite(Astronaut)
tiles.setCurrentTilemap(tilemap`level0`)
tiles.placeOnRandomTile(Astronaut, sprites.castle.rock0)
game.showLongText("Welcome to Mission: Universe.", DialogLayout.Top)
game.showLongText("Use the Arrow Keys to Move and Space to Jump ", DialogLayout.Top)
game.showLongText("Your Job is to collect information about the universe for the government", DialogLayout.Top)
game.showLongText("But beware of the evil alien organization; Goober ", DialogLayout.Top)
game.showLongText("They are trying to steal information to take over the world", DialogLayout.Top)
spawn_enemies()
game.onUpdate(function () {
    if ((Astronaut.isHittingTile(CollisionDirection.Left) || Astronaut.isHittingTile(CollisionDirection.Right)) && Astronaut.vy >= 0) {
        Astronaut.vy = 0
        Astronaut.ay = 0
    } else {
        Astronaut.ay = 250
    }
    if (Astronaut.vx < 0 || Astronaut.isHittingTile(CollisionDirection.Left)) {
    	
    }
    Astronaut.setImage(Astronaut.image)
    if (Astronaut.vx < 0) {
    	
    }
    for (let value of sprites.allOfKind(SpriteKind.newalien)) {
        if (value.isHittingTile(CollisionDirection.Left)) {
            alien2.vx = 50
        }
        if (value.isHittingTile(CollisionDirection.Right)) {
            alien2.vx = -50
        }
    }
})
